config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :categories do
    resources :messages, only: %i[new create destroy]
    member do
      patch :publish
    end
  end

  namespace :admin do
    resources :users, only: [:index] do
      member do
        patch :change_role
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :moderator
      can :manage, [Category, Message]
    elsif user.has_role? :user
      can :manage, [Category, Message], user_id: user.id
      cannot :publish, Category
    end
    can :read, [Category, Message]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  resourcify
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 1000 }

  default_scope { order(id: :desc) }
  scope :published, (-> { where(published: true) })

  has_many :messages
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  resourcify
  validates :content, presence: true, length: { maximum: 1000 }

  belongs_to :user
  belongs_to :category
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :assign_role
  validates :name, presence: true

  has_attached_file :avatar, styles: { medium: '200x200>', thumb: '100x100>' },
                             default_url: ':style/missing.png'
  validates_attachment :avatar, content_type: { content_type: ['image/jpeg', 'image/gif', 'image/png'] },
                                size: { less_than: 1.megabytes }

  has_many :categories
  has_many :messages

  def assign_role
    add_role(:user) if roles.blank?
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    load_and_authorize_resource

    def index
      @users = User.paginate(page: params[:page], per_page: 10)
    end

    def change_role
      @user = User.find(params[:id])

      if @user.has_role? :user
        assign_new_role(:user, :moderator)
      else
        assign_new_role(:moderator, :user)
      end

      redirect_to admin_users_path, notice: 'Role changed!'
    end

    private

    def assign_new_role(old_role, new_role)
      @user.remove_role old_role
      @user.add_role new_role
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to root_path, alert: 'Access Denied!'
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include ApplicationHelper

  load_and_authorize_resource
  before_action :authenticate_user!, except: %i[index show]
  before_action :initialize_category, except: %i[index new create]

  def index
    @categories = if check_role? %i[admin moderator]
                    Category.paginate(page: params[:page], per_page: 10)
                  else
                    Category.published.paginate(page: params[:page], per_page: 10)
                  end
  end

  def new
    @category = Category.new
  end

  def show
    unless @category.published
      redirect_to categories_path, alert: 'The category is not published yet!'
    end
    @messages = @category.messages.paginate(page: params[:page], per_page: 10).order(:id)
  end

  def create
    @category = current_user.categories.new(category_params)

    if @category.save
      redirect_to categories_path, notice: 'Your category is reviewing by moderator.'
    else
      render :new
    end
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def edit; end

  def destroy
    @category.messages.each(&:destroy!)
    @category.destroy

    redirect_to categories_path
  end

  def publish
    Category.update(@category.id, published: !@category.published)
    redirect_to categories_path, notice: 'Updated!'
  end

  private

  def category_params
    params.require(:category).permit(:title, :body)
  end

  def initialize_category
    @category = Category.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!

  def new
    @message = Message.new
  end

  def create
    @message = current_user.messages.new(message_params)
    @message.category = Category.find(params[:category_id])

    redirect_to @message.category if @message.save
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    redirect_to @message.category
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :avatar, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :avatar, :password, :password_confirmation, :current_password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @clients_count = User.all.count
    @categories_count = Category.published.count
    @messages_count = Message.count
    @roles_count = Role.all.count
    @last_categories = Category.published.limit(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = 'Forum'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end

  def check_role?(roles)
    if user_signed_in?
      roles.each do |role|
        return true if current_user.has_role? role
      end
    end
    false
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/users/index.html.slim
- provide(:title, 'Users')
h1 Users
table.table.table-bordered
  thead
    tr
      th Name
      th Role
      th Email
      th Action
  tbody
    - @users.each do |user|
      tr
        td
          = user.name
        td
          = user.roles.first.name.capitalize
        td
          = user.email
        td
          - if user.has_role? :user
            - link = 'Moderator'
          - elsif user.has_role? :moderator
            - link = 'User'
          - unless user.has_role? :admin
            = link_to "Make #{link}", change_role_admin_user_path(user), method: :patch, class: 'btn btn-primary'
          - else
            = 'You are admin'
= will_paginate @users, renderer: BootstrapPagination::Rails

app/views/categories/edit.html.slim
- provide(:title, 'Edit Category')
h1 Edit Category
= form_for @category do |f|
  - if @category.errors.any?
    .alert.alert-danger
      - @category.errors.full_messages.each do |message|
        = message
        br
  p
    = f.label :title
    = f.text_field :title, value: @category.title, class: 'form-control'
  p
    = f.label :body, 'Problem'
    = f.text_area :body, value: @category.body, class: 'form-control', rows: 10
  = f.submit 'Update', class: 'btn btn-primary'

app/views/categories/index.html.slim
- provide(:title, 'Categories')
h1 Categories
- if user_signed_in?
  = link_to 'Create', new_category_path, class: 'btn btn-success'
br
br

= will_paginate @categories, renderer: BootstrapPagination::Rails
.table-responsive
  table.table.table-bordered.table-hover
    tr.active
      th.width_15
        h4 Category
      th.width_15
        h4 Author
      th.width_20
        h4 Date
      th.width_15 colspan='3'
        h4 Actions
    - @categories.each do |category|
      tr.info
        td
          = link_to " #{category.title}", category_path(category), class: 'glyphicon glyphicon-comment'
        td
          - if category.user
            = category.user.name
          - else
            = 'Author has been deleted.'
        td
          = category.created_at.localtime.strftime("%d/%m/%Y at %r")
        - if check_role?([:admin, :moderator]) || (current_user == category.user && user_signed_in?)
          td
            = link_to 'Edit', edit_category_path(category), class: 'btn btn-primary'
          td
            = link_to 'Delete', category, method: :delete, data: {confirm: 'You sure?'}, class: 'btn btn-danger'
          - if check_role? [:admin, :moderator]
            td
              - if category.published
                - text_url = 'Hide'
              - else
                - text_url = 'Publish'
              = link_to "#{text_url}", publish_category_path(category), method: :patch, class: 'btn btn-success'
        - else
          td
            = 'You are not author'
          td
- if @categories.length == 0
  h4 Categories list is empty...

app/views/categories/new.html.slim
- provide(:title, 'Add Category')
h1 Add Category
= form_for @category do |f|
  - if @category.errors.any?
    .alert.alert-danger
      - @category.errors.full_messages.each do |message|
        = message
        br
  p
    = f.label :title
    = f.text_field :title, class: 'form-control'
  p
    = f.label :body, 'Problem'
    = f.text_area :body, class: 'form-control', rows: 10
  = f.submit 'Add', class: 'btn btn-success'

app/views/categories/show.html.slim
- provide(:title, @category.title)
.title
  h3
    = @category.title
hr
p
  span.glyphicon-glyphicon-time
    = "Posted on #{@category.created_at.localtime.strftime('%d/%m/%Y at %r')}"
hr
.detailBox
  .titleBox
    label Problem
  .commentBox
    p
      pre
        = @category.body
  .titleBox
    label
      = "Comments(#{@messages.length})"
    - @messages.each do |message|
      .media
        .comment
          span.pull-left.ava
            = image_tag message.user.avatar.url(:thumb), width: 100, height: 100
          .media-body
            h4.media-heading
              - if message.user
                = message.user.name
              small
                = " #{message.created_at.localtime.strftime("%d/%m/%Y at %r")}"
            pre
              = message.content
              - if check_role?([:admin, :moderator]) || (current_user == message.user && user_signed_in?)
                = link_to '', category_message_url(@category, message), method: :delete,
                        data: {confirm: 'You sure?'}, class: 'glyphicon glyphicon-remove'
    = will_paginate @messages, renderer: BootstrapPagination::Rails
    br
    - if user_signed_in?
      = form_for [@category, @category.messages.build], :html => {:class => 'form-inline'} do |f|
        .form-group
          = f.text_area :content, :placeholder => 'Your comment...', class: 'form-control', cols: 173, rows: 5
        = f.submit 'Add', class: 'btn btn-primary'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_title(yield(:title))
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = favicon_link_tag 'favicon.ico'
    = csrf_meta_tags
    link href="//fonts.googleapis.com/css?family=Roboto:100,300,400,500,700%7CPlayfair+Display:400,700,700i,900,900i" rel="stylesheet" type="text/css" /

  body
    = render 'layouts/shared/header'
    div.container
      - if notice
        .alert.alert-info
          = notice
      - if alert
        .alert.alert-warning
          = alert
      = yield
      = render 'layouts/shared/footer'

app/views/layouts/shared/_footer.html.slim
footer.page-foot.bg-cape-cod.context-dark
  section.section-40.section-sm-75
    .shell
      .range.range-xs-center
        .cell-xs-9.cell-sm-11.cell-lg-12
          .range
            .cell-sm-6.cell-md-10.cell-lg-3
              .inset-lg-right-20 style=("max-width: 510px;")
                p.offset-top-22.text-dusty-gray EasyAudit delivers environment through which high-quality firms from diverse backgrounds can work together toward their own common goals.
                a.text-small-16.text-medium.offset-top-15 href="#"  Free Consultation
            .cell-sm-6.cell-md-4.cell-lg-3.offset-top-50.offset-sm-top-0.offset-md-top-50.offset-lg-top-0
              h6.text-small-16.text-uppercase Recent Categories
              .offset-top-22.offset-md-top-30
                article.post.post-preview.post-preview-inverse.offset-top-22
                  a href="#"
                  .unit.unit-horizontal.unit-spacing-lg
                    .unit-body
                      .post-header
                        p Top 3 Concerns Whe Choosing a Cloud Vendor
                      .post-meta
                        ul.list-meta
                          li
                            time datetime="2016-12-23"  June 23, 2016
                          li 4 Comment
                article.post.post-preview.post-preview-inverse.offset-top-22
                  a href="#"
                  .unit.unit-horizontal.unit-spacing-lg
                    .unit-body
                      .post-header
                        p Audit Data Analytics: Why Auditors Should Care
                      .post-meta
                        ul.list-meta
                          li
                            time datetime="2016-12-23"  June 20, 2016
                          li 4 Comment
            .cell-sm-6.cell-md-4.cell-lg-3.offset-top-50.offset-lg-top-0
              h6.text-small-16.text-uppercase Quick links
              .row.offset-top-22.offset-md-top-30 style=("max-width: 270px;")
                .col-xs-6
                  ul.list-marked-variant-2
                    li
                      a href="#"  Home
                    li
                      a href="#"  Services
                    li
                      a href="#"  Careers
                    li
                      a href="#"  Blog
                .col-xs-6
                  ul.list-marked-variant-2
                    li
                      a href="#"  About us
                    li
                      a href="#"  Contacts
                    li
                      a href="#"  Appointment
            .cell-sm-6.cell-md-4.cell-lg-3.offset-top-50.offset-lg-top-0
              h6.text-small-16.text-uppercase Contact us
              address.contact-info.offset-top-22.offset-md-top-30.offset-lg-top-35.text-left
              .unit.unit-horizontal.unit-spacing-md.unit-middle
                .unit-left
                  span.icon.icon-xs.icon-dusty-gray.material-icons-phone
                .unit-body
                  a.link-white href="callto:#"  +1 (409) 987–5874
              .unit.unit-horizontal.unit-spacing-md.unit-middle.offset-top-15
                .unit-left
                  span.icon.icon-xs.icon-dusty-gray.fa.fa-envelope-o
                .unit-body
                  a.link-white href="#"
                    span.__cf_email__ data-cfemail="365f5850597652535b595a5f585d18594451"  [email protected]
              .unit.unit-horizontal.unit-spacing-md.offset-top-15
                .unit-left
                  span.icon.icon-xs.icon-dusty-gray.material-icons-place
                .unit-body
                  a.link-white.reveal-inline href="#"
                    | 6036 Richmond hwy,
                    br>/
                    | Alexandria, VA USA 22303
  .shell
    hr.hr.bg-abbey-04
  section.section-35
    .shell.text-center
      .range.range-sm-justify
        .cell-sm-6.offset-top-15.offset-sm-top-0.text-sm-left
          p.rights.text-white
            span#copyright-year
            span &nbsp;©&nbsp;
            span SoftGroup.&nbsp;
            a.link-white-v2 href="#"  Privacy Policy

app/views/layouts/shared/_header.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand.glyphicon.glyphicon-blackboard href=root_path  ForumOk
    #navbar.collapse.navbar-collapse
      ul.nav.navbar-nav
        li
          = link_to " Home", root_path, class: 'glyphicon glyphicon-home'
        li
          = link_to " Forum", categories_path, class: 'glyphicon glyphicon-list-alt'
        - if check_role? [:admin]
          li
            = link_to " Users", admin_users_path, class: 'glyphicon glyphicon-cog'
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li
            = link_to " Profile", edit_user_registration_path, class: 'glyphicon glyphicon-user'
          li
            = link_to " Logout", destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out'
        - else
          li
            = link_to " Sign-Up", new_user_registration_path, class: 'glyphicon glyphicon-user'
          li
            = link_to " Login", new_user_session_path, class: 'glyphicon glyphicon-log-in'
br
br
br

app/views/layouts/shared/design/_article-section.html.slim
section
  .range.range-condensed.range-xs-center.range-sm-left
    .cell-xs-10.cell-sm-4.height-fill
      article.icon-box.icon-box-top-line
        .box-top
          .box-icon
            span.icon.icon-primary.icon-lg.icon-1
          .box-header
            h5
              a href="#"  Internal Audit
        .box-body
          p.text-gray-base Audit services are designed to help your business mitigate risk, create new efficiencies and better support strategic objectives.
        a.btn.btn-icon-only.btn-icon-single.btn-icon-default href="#"
          span.glyphicon.glyphicon-menu-right
    .cell-xs-10.cell-sm-4.height-fill.offset-top-40.offset-sm-top-0
      article.icon-box.icon-box-top-line
        .box-top
          .box-icon
            span.icon.icon-primary.icon-lg.icon-2
          .box-header
            h5
              a href="#"  Accounting
        .box-body
          p.text-gray-base A range of services designed to provide timely preparation of company accounts, whether it be at the financial year end or on a monthly basis.
        a.btn.btn-icon-only.btn-icon-single.btn-icon-default href="#"
          span.glyphicon.glyphicon-menu-right
    .cell-xs-10.cell-sm-4.height-fill.offset-top-40.offset-sm-top-0
      article.icon-box.icon-box-top-line
        .box-top
          .box-icon
            span.icon.icon-primary.icon-lg.icon-3
          .box-header
            h5
              a href="#"  Audit
        .box-body
          p.text-gray-base Audits are verified by sight, confirmation, discussion with management, assessment of internal controls and analytical procedures.
        a.btn.btn-icon-only.btn-icon-single.btn-icon-default href="#"
          span.glyphicon.glyphicon-menu-right
    .cell-xs-10.cell-sm-4.height-fill.offset-top-40.offset-sm-top-0
      article.icon-box
        .box-top
          .box-icon
            span.icon.icon-primary.icon-lg.icon-4
          .box-header
            h5
              a href="#"  Legislative Support
        .box-body
          p.text-gray-base To ensure the quality and effectiveness of every business activity, we support our every client by supporting them in all legislative issues.
        a.btn.btn-icon-only.btn-icon-single.btn-icon-default href="#"
          span.glyphicon.glyphicon-menu-right
    .cell-xs-10.cell-sm-4.height-fill.offset-top-40.offset-sm-top-0
      article.icon-box
        .box-top
          .box-icon
            span.icon.icon-primary.icon-lg.icon-5
          .box-header
            h5
              a href="#"  Review
        .box-body
          p.text-gray-base Reviews are less detailed and consist predominantly of an assessment of the company`s books and records.
        a.btn.btn-icon-only.btn-icon-single.btn-icon-default href="#"
          span.glyphicon.glyphicon-menu-right
    .cell-xs-10.cell-sm-4.height-fill.offset-top-40.offset-sm-top-0
      article.icon-box
        .box-top
          .box-icon
            span.icon.icon-primary.icon-lg.icon-6
          .box-header
            h5
              a href="#"  Attest Services
        .box-body
          p.text-gray-base Attestation services that we provide, include the process of independent review of the data validity audited by an accountant.
        a.btn.btn-icon-only.btn-icon-single.btn-icon-default href="#"
          span.glyphicon.glyphicon-menu-right

app/views/layouts/shared/design/_count-section.html.slim
section.section-with-counters.bg-primary.text-center
  .shell.bg-cape-cod.context-dark.section-60.section-md-90
    h4.text-rolling-stone.text-bold.text-uppercase Looking for
    h3.offset-top-2
      span.text-thin a First-Class
      | forum?
    p.text-white Here is it!
    .range.offset-top-60.list-md-dashed
      .cell-sm-3
        .h1.small.counter-bold.counter
          = clients_count
        .offset-top-0.text-bold.text-white.text-uppercase Trusted Clients
      .cell-sm-3.offset-top-40.offset-sm-top-0
        .h1.small.counter-bold.counter
          = categories_count
        .offset-top-0.text-bold.text-white.text-uppercase Topics
      .cell-sm-3.offset-top-40.offset-sm-top-0
        .h1.small.counter-bold.counter
          = messages_count
        .offset-top-0.text-bold.text-white.text-uppercase Messages
      .cell-sm-3.offset-top-40.offset-sm-top-0
        .h1.small.counter-bold.counter
          = roles_count
        .offset-top-0.text-bold.text-white.text-uppercase Roles
    .offset-top-50.offset-md-top-75.inset-xs-left-60.inset-xs-right-60
      .reveal-sm-flex.range-sm-center.range-sm-middle
        = link_to 'See All Topics', categories_path, class: 'btn btn-rect btn-primary reveal-block reveal-sm-inline-block'

app/views/layouts/shared/design/_latest-topics-section.html.slim
section.section-50.section-sm-90.section-sm-bottom-100
  .shell.text-center
    h3
      | Latest Topics
    .range.range-xs-center.offset-top-40
      - last_categories.each do |category|
        .cell-xs-8.cell-sm-7.cell-md-4
          .post-boxed.reveal-lg-inline-block
            .post-boxed-caption
              .post-boxed-title.text-bold
                = link_to "#{category.title}", category_path(category)
              .offset-top-5
                ul.list-inline.list-inline-dashed.text-uppercase
                  li
                    = category.created_at.localtime.strftime('%^B %d, %Y')
                  li
                    span
                      = "by #{category.user.name}"

app/views/layouts/shared/design/_page-container.html.slim
.page
  = render 'layouts/shared/design/swiper-section'
  = render 'layouts/shared/design/article-section'
  = render partial: 'layouts/shared/design/count-section', locals: { clients_count: @clients_count,
          categories_count: @categories_count,
          messages_count: @messages_count,
          roles_count: @roles_count }
  = render partial: 'layouts/shared/design/latest-topics-section', locals: { last_categories: @last_categories }

app/views/layouts/shared/design/_swiper-section.html.slim
section
  .swiper-container.swiper-slider.swiper-variant-.bg-gray-base data-autoplay="false" data-loop="false" data-simulate-touch="true"
    .swiper-wrapper.text-center
      .swiper-slide
        .swiper-slide-caption
          .shell
            .range.range-xs-center
              .cell-sm-11.cell-md-10
                .text-white.text-uppercase.jumbotron-custom.border-modern data-caption-animate="fadeInUp" data-caption-delay="0s"
                  | Welcome to the ForumOk!
                .offset-sm-top-5 data-caption-animate="fadeInUp" data-caption-delay="450s"
                  p.text-big-19.text-white.veil.reveal-sm-inline-block
                    | Here you can discussing whatever!
                - unless user_signed_in?
                  .offset-top-27 data-caption-animate="fadeInUp" data-caption-delay="550s"
                    = link_to 'Sign-Up', new_user_registration_path, class: 'btn btn-primary'

app/views/static_pages/home.html.slim
= render 'layouts/shared/design/page-container'